/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var LetsGo:String = "event:/Music/LetsGo";
}

class FmodSFX {
    public static inline var AnnouncerGo:String = "event:/SFX/Announcer/AnnouncerGo";
    public static inline var AnnouncerReady:String = "event:/SFX/Announcer/AnnouncerReady";
    public static inline var AnnouncerSet:String = "event:/SFX/Announcer/AnnouncerSet";
    public static inline var BallTerrain:String = "event:/SFX/Ball/BallTerrain";
    public static inline var BoxPlace:String = "event:/SFX/Box/BoxPlace";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var PlayerDie:String = "event:/SFX/Player/PlayerDie";
    public static inline var PlayerReload:String = "event:/SFX/Player/PlayerReload";
    public static inline var PlayerShoot:String = "event:/SFX/Player/PlayerShoot";
    public static inline var PlayerShootEmpty:String = "event:/SFX/Player/PlayerShootEmpty";
}
